### ISSUE TITLE
Docker build for Raspberry Pi failing

### ISSUE THREAD

**Issue by TzionCastillo1** [Serafadam/depthai_ros_driver#31]
Hi,

I am following the steps from the readme, but when I attempt to build the container using vscode, i encounter this error:
```=> ERROR [2/7] RUN apt-get update    && apt-get -y install --no-install-  2.2s
                                                                                
[+] Building 4.2s (6/11)                                                        
 => [internal] load build definition from Dockerfile                       0.2s
 => => transferring dockerfile: 1.05kB                                     0.0s
 => [internal] load .dockerignore                                          0.2s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/amd64/ros:foxy-ros-base         1.2s
 => CACHED [1/7] FROM docker.io/amd64/ros:foxy-ros-base@sha256:add9970136  0.0s
 => [internal] load build context                                          0.2s
 => => transferring context: 28B                                           0.0s
 => ERROR [2/7] RUN apt-get update    && apt-get -y install --no-install-  2.2s
[2022-09-30T18:32:13.287Z] ------
 > [2/7] RUN apt-get update    && apt-get -y install --no-install-recommends software-properties-common libusb-1.0-0-dev wget zsh:
#0 1.973 exec /bin/sh: exec format error
------
error: failed to solve: executor failed running [/bin/sh -c apt-get update    && apt-get -y install --no-install-recommends software-properties-common libusb-1.0-0-dev wget zsh]: exit code: 1
[2022-09-30T18:32:13.370Z] Stop (6307 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/navigator/depthai_ros_driver/.devcontainer/Dockerfile -t vsc-depthai_ros_driver-8f4b036111cbb983edcaf80cc60bfb11 --build-arg WORKSPACE=/workspaces/depthai_ros_driver /home/navigator/depthai_ros_driver/.devcontainer
[2022-09-30T18:32:13.428Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/navigator/depthai_ros_driver/.devcontainer/Dockerfile -t vsc-depthai_ros_driver-8f4b036111cbb983edcaf80cc60bfb11 --build-arg WORKSPACE=/workspaces/depthai_ros_driver /home/navigator/depthai_ros_driver/.devcontainer
[2022-09-30T18:32:13.429Z]     at HS (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:256:1490)
[2022-09-30T18:32:13.460Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-30T18:32:13.528Z]     at async Cu (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2801)
[2022-09-30T18:32:13.529Z]     at async Zw (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:1779)
[2022-09-30T18:32:13.530Z]     at async KS (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[2022-09-30T18:32:13.530Z]     at async co (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[2022-09-30T18:32:13.531Z]     at async LP (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[2022-09-30T18:32:13.532Z]     at async DP (/home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[2022-09-30T18:32:13.619Z] Stop (9186 ms): Run: /usr/share/code/code /home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/navigator/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/navigator/depthai_ros_driver --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/navigator/depthai_ros_driver --log-level debug --log-format json --config /home/navigator/depthai_ros_driver/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-30T18:32:13.622Z] Exit code 1
[2022-09-30T18:32:13.772Z] Command failed: /usr/share/code/code /home/navigator/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/navigator/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/navigator/depthai_ros_driver --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/navigator/depthai_ros_driver --log-level debug --log-format json --config /home/navigator/depthai_ros_driver/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-30T18:32:13.775Z] Exit code 1
```

Any help is appreciated.

**Comment by Serafadam** [comment]
Hi, I am currently on vacation so I'm unable to get to my RPi, but please write a few things so that it's easier to debug:
Which RPi do you have? 
Are you opening VSCode on RPi or via remote extension?
I haven't really tested building on RPi via VSCode, just on normal PC, if you build the RPiDockerfile it should build the image just fine

**Comment by TzionCastillo1** [comment]
No worries. It looks like it was building from the x86 dockerfile instead of the one for the raspberry pi. I Renamed the files again and all worked.
Thanks for your help!
